name = input("enter your name")
branch = input("enter your branch")
gender = input("enter your gender")
college = input("enter your college name")
age = input('enter your age')
print("Name:",name)
print("Age:",age)
print("Gender:",gender)
print("college:",college)
print("age:",age)
